### ISSUE TITLE
Training probelm

### ISSUE THREAD

**Issue by MoExplorer** [JiajianZeng/caffe-landmark#1]
Nice work. But I have some problems that I hope you can help me solve. 

First, I have NOT found out the pre-trained contextual network, namely Alexnet in the experiment directory.

Second, dose  the VGG_PERCEP_STRUCT mean that it is "base+context+struct" based on VGG net?

Third, could you please give us the detailed training /testing mannual so that we can know how to train/test your code?

Thanks

**Comment by JiajianZeng** [comment]
1. The pre-trained contextual network will be released soon (as well as the datasets).
2. Yes, u are right.
3. The detailed training/testing instructions will be provided in the near future (sorry about that, I am working on my master's thesis these days).
@MoExplorer

**Comment by MoExplorer** [comment]
@JiajianZeng OK, Thanks for your reply. I'm looking forward to that.

**Comment by xuguozhi** [comment]
Waiting for you further contributions, and hoping everything going well to you!

**Comment by JiajianZeng** [comment]
@xuguozhi Thanks.
