### ISSUE TITLE
训练中euclidean loss、perceptual losss、structual loss的值比率问题

### ISSUE THREAD

**Issue by janicevidal** [JiajianZeng/caffe-landmark#2]
![snipaste_20180420_141457](https://user-images.githubusercontent.com/29887681/39033565-3ef52b54-44a5-11e8-8d26-19ef824c9dd3.png)

五点网络预测

如 上图，三个loss值当中，euclidean_loss、perceptual_losss、structual_loss按10：0.1：1的比例训练，perceptual_losss的值仍然是占大头的，后期的训练中euclidean_loss值基本就不会变了，loss的下降主要也是perceptual_losss的减小。如果此时减小学习率，euclidean_loss会降一点，但同时perceptual_losss的降低会越来越慢，十万次迭代下降的范围还达不到学习率下降前一万次迭代的水平，structual_loss的值起到的作用也越来越小，structual_loss值比euclidean_loss值小一个量级。

在我的想法中，euclidean_loss应该是回归问题中所要优化的主要loss函数，这个比例的设置是不是存在一些问题，还是要等到perceptual_losss的值收敛到100*euclidean_loss值水平的时候降低学习率，网络的测试结果也并没有体现出添加loss函数之后网络的优势，最终网络收敛时的loss值大概的一个比例关系能不能分享一下，谢谢！

**Comment by JiajianZeng** [comment]
您好！您的邮件我已收到.
